"""empty message

Revision ID: 21d42b5d8701
Revises: d701534eae5d
Create Date: 2025-02-15 18:36:20.207105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d42b5d8701'
down_revision = 'd701534eae5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift', sa.Column('start_date', sa.Date(), nullable=False))
    op.drop_column('shift', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_column('shift', 'start_date')
    # ### end Alembic commands ###
