"""empty message

Revision ID: 88cc244be225
Revises: 21d42b5d8701
Create Date: 2025-02-17 00:24:32.419934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cc244be225'
down_revision = '21d42b5d8701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('menba', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('yakiba', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('checkout', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sikomi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sikomi')
    op.drop_column('users', 'checkout')
    op.drop_column('users', 'yakiba')
    op.drop_column('users', 'menba')
    # ### end Alembic commands ###
