"""empty message

Revision ID: c4a8eba29c92
Revises: deef39772afa
Create Date: 2025-02-17 23:12:00.337333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a8eba29c92'
down_revision = 'deef39772afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift', sa.Column('break_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift', 'break_time')
    # ### end Alembic commands ###
