"""empty message

Revision ID: d701534eae5d
Revises: bd8408b8e341
Create Date: 2025-02-15 18:23:31.988509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd701534eae5d'
down_revision = 'bd8408b8e341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
