"""empty message

Revision ID: deef39772afa
Revises: 88cc244be225
Create Date: 2025-02-17 15:20:09.887535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deef39772afa'
down_revision = '88cc244be225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'start_time',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('shift', 'end_time',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'end_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('shift', 'start_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
